(function(){
  const d=document;let overlay,media,caption,items=[],index=0,startX=0;
  function visibleTriggers(){return [...d.querySelectorAll('.lightbox-trigger')].filter(el=>el.offsetParent!==null&&!el.classList.contains('hidden'));}
  function icon(){return '<div class="ph-inner"><span class="camera">📷</span><span class="ph-caption">'+(items[index]?.dataset.caption||'TDC Photo')+'</span></div>';}
  function render(){const el=items[index]; if(!el)return; const img=el.querySelector('img'); caption.textContent=el.dataset.caption||img?.alt||'TDC Photo'; media.innerHTML=''; if(img&&img.getAttribute('src')){const clone=new Image(); clone.src=img.src; clone.alt=caption.textContent; media.appendChild(clone);}else{media.innerHTML=icon();}}
  function open(el){items=visibleTriggers(); index=Math.max(0,items.indexOf(el)); overlay.classList.add('open'); overlay.setAttribute('aria-hidden','false'); d.body.style.overflow='hidden'; render();}
  function close(){overlay.classList.remove('open'); overlay.setAttribute('aria-hidden','true'); d.body.style.overflow='';}
  function nav(dir){if(!items.length)return; index=(index+dir+items.length)%items.length; render();}
  function init(){overlay=d.createElement('div'); overlay.className='lightbox-overlay'; overlay.setAttribute('aria-hidden','true'); overlay.innerHTML='<button class="lightbox-close" aria-label="Close">×</button><button class="lightbox-arrow lightbox-prev" aria-label="Previous">‹</button><div class="lightbox-stage"><div class="lightbox-media"></div><div class="lightbox-caption"></div></div><button class="lightbox-arrow lightbox-next" aria-label="Next">›</button>'; d.body.appendChild(overlay); media=overlay.querySelector('.lightbox-media'); caption=overlay.querySelector('.lightbox-caption'); d.addEventListener('click',e=>{const t=e.target.closest('.lightbox-trigger'); if(t){open(t)} }); overlay.addEventListener('click',e=>{if(e.target===overlay)close()}); overlay.querySelector('.lightbox-close').onclick=close; overlay.querySelector('.lightbox-prev').onclick=()=>nav(-1); overlay.querySelector('.lightbox-next').onclick=()=>nav(1); d.addEventListener('keydown',e=>{if(!overlay.classList.contains('open'))return; if(e.key==='Escape')close(); if(e.key==='ArrowLeft')nav(-1); if(e.key==='ArrowRight')nav(1);}); overlay.addEventListener('touchstart',e=>{startX=e.changedTouches[0].screenX},{passive:true}); overlay.addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-startX; if(Math.abs(dx)>45)nav(dx>0?-1:1);},{passive:true});}
  d.addEventListener('DOMContentLoaded',()=>{init(); d.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{const group=btn.closest('.filter-group'); group.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); const f=btn.dataset.filter; d.querySelectorAll('[data-category]').forEach(card=>{const cats=(card.dataset.category||'').split(' '); card.classList.toggle('hidden',f!=='all'&&!cats.includes(f));});})); d.querySelectorAll('.read-more').forEach(b=>b.addEventListener('click',()=>{const body=b.closest('.card').querySelector('.article-body'); body.classList.toggle('open'); b.textContent=body.classList.contains('open')?'Show less':'Read full story';})); d.querySelector('.hamb')?.addEventListener('click',()=>d.querySelector('.nav-links')?.classList.toggle('open'));});
})();
